'use strict';
const fs=require('fs');
const path=require('path');
const cp=require('child_process');
const {chromium}=require('playwright');
const ROOT=process.cwd();
const HOUSE='/tmp/house';
const SERVE='/tmp/lideres-visual';
const OUT='/tmp/visual-audit';
const KEY='/tmp/visual-key.pem';
const CERT='/tmp/visual-cert.pem';
const SERVER='/tmp/visual-server.cjs';
function run(cmd,args,opts={}){const r=cp.spawnSync(cmd,args,{stdio:'inherit',...opts});if(r.status!==0)throw new Error(cmd+' failed');}
function copyTree(src,dst){fs.rmSync(dst,{recursive:true,force:true});fs.cpSync(src,dst,{recursive:true,filter:p=>!p.includes(path.sep+'.git'+path.sep)&&!p.endsWith(path.sep+'.git')});}
function prep(){copyTree(ROOT,SERVE);fs.mkdirSync(OUT,{recursive:true});const rows=[];for(let i=0;i<28;i++){rows.push({data:'2026-08-'+String(10+(i%20)).padStart(2,'0'),unidade:'Itaim',status:'finalizado',resumo:'Frango '+(i%7),custo_total:420+i,desperdicio_total:i%3,aval_geral:4.5,n_avaliacoes:4,pratos:[{tipo:'principal',item:'Frango '+(i%7)}],comentarios:[]});}
const gate=`document.documentElement.dataset.auth='ok';window.__lideresSession={displayName:'Gestão TATÁ',perfil:'admin'};window.__lideresSupa={schema:function(){return {rpc:async function(){return {data:${JSON.stringify(rows)},error:null}}}}};`;
fs.writeFileSync(path.join(SERVE,'compliance/gate.js'),gate);
for(const f of ['compliance/kpis/tatahouse/planejador-v2.html','compliance/kpis/tatahouse/central.html']){let h=fs.readFileSync(path.join(SERVE,f),'utf8');h=h.replace(/<script src="https:\/\/cdn\.jsdelivr\.net\/npm\/@supabase\/supabase-js@2\/dist\/umd\/supabase\.js"><\/script>/g,'');fs.writeFileSync(path.join(SERVE,f),h);}
run('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',KEY,'-out',CERT,'-days','1','-subj','/CN=localhost','-addext','subjectAltName=DNS:lideres.tatasushi.tech,DNS:tata-house.github.io']);
run('sudo',['sh','-c',"grep -q 'lideres.tatasushi.tech' /etc/hosts || printf '\n127.0.0.2 lideres.tatasushi.tech\n127.0.0.3 tata-house.github.io\n' >> /etc/hosts"]);
fs.writeFileSync(SERVER,`'use strict';const https=require('https'),fs=require('fs'),path=require('path');const root=path.resolve(process.argv[2]),host=process.argv[3];const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2'};function safe(u){let p=decodeURIComponent(new URL(u,'https://local').pathname);if(p.endsWith('/'))p+='index.html';let f=path.resolve(root,'.'+p);if(!f.startsWith(root))return null;if(!fs.existsSync(f)&&!path.extname(f)&&fs.existsSync(f+'.html'))f+='.html';if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');return f;}https.createServer({key:fs.readFileSync('${KEY}'),cert:fs.readFileSync('${CERT}')},(q,r)=>{const f=safe(q.url);if(!f||!fs.existsSync(f)){r.writeHead(404);return r.end('404')}r.writeHead(200,{'content-type':mime[path.extname(f)]||'application/octet-stream','cache-control':'no-store'});fs.createReadStream(f).pipe(r)}).listen(443,host);`);
cp.spawn('sudo',[process.execPath,SERVER,SERVE,'127.0.0.2'],{detached:true,stdio:'ignore'}).unref();cp.spawn('sudo',[process.execPath,SERVER,path.join(HOUSE,'out'),'127.0.0.3'],{detached:true,stdio:'ignore'}).unref();}
async function shot(browser,width,height,label){const ctx=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width,height}});const page=await ctx.newPage();await page.route('**/fonts.googleapis.com/**',r=>r.abort());await page.route('**/fonts.gstatic.com/**',r=>r.abort());
await page.goto('https://lideres.tatasushi.tech/compliance/kpis/tatahouse/central.html',{waitUntil:'domcontentloaded'});await page.waitForTimeout(900);await page.screenshot({path:path.join(OUT,label+'-central.png'),fullPage:true});const central={overflow:await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth),nav:await page.locator('.nav').innerText(),status:await page.locator('#central-status').innerText()};
await page.goto('https://lideres.tatasushi.tech/compliance/kpis/tatahouse/planejador-v2.html',{waitUntil:'domcontentloaded'});await page.selectOption('#unidade','Itaim');await page.fill('#semana','2026-W37');await page.screenshot({path:path.join(OUT,label+'-planner-start.png'),fullPage:true});await page.click('#abrir');const iframe=page.locator('#house-frame');await iframe.waitFor({state:'visible'});const frame=page.frames().find(f=>f.url().includes('tata-house.github.io/planejar'));
if(frame){try{await frame.getByTestId('evidencia-readonly-lideres').waitFor({state:'visible',timeout:15000});}catch{};await page.screenshot({path:path.join(OUT,label+'-planner-active.png'),fullPage:true});}
const planner={overflow:await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth),hero:await page.locator('.hero').innerText(),status:await page.locator('#status').innerText()};await ctx.close();return {central,planner};}
(async()=>{prep();for(let i=0;i<40;i++){const a=cp.spawnSync('curl',['-ks','--resolve','lideres.tatasushi.tech:443:127.0.0.2','-o','/dev/null','-w','%{http_code}','https://lideres.tatasushi.tech/compliance/kpis/tatahouse/central.html'],{encoding:'utf8'});const b=cp.spawnSync('curl',['-ks','--resolve','tata-house.github.io:443:127.0.0.3','-o','/dev/null','-w','%{http_code}','https://tata-house.github.io/planejar.html'],{encoding:'utf8'});if(a.stdout==='200'&&b.stdout==='200')break;await new Promise(r=>setTimeout(r,250));}
const browser=await chromium.launch({headless:true,args:['--no-proxy-server']});const desktop=await shot(browser,1440,1000,'desktop');const mobile=await shot(browser,390,844,'mobile');await browser.close();fs.writeFileSync(path.join(OUT,'audit.json'),JSON.stringify({desktop,mobile},null,2));console.log('VISUAL_AUDIT_SCREENSHOTS=PASS');console.log('VISUAL_AUDIT_DESKTOP_OVERFLOW='+desktop.central.overflow+'/'+desktop.planner.overflow);console.log('VISUAL_AUDIT_MOBILE_OVERFLOW='+mobile.central.overflow+'/'+mobile.planner.overflow);})().catch(e=>{console.error(e.stack||e);process.exit(1)});